export const scaleLabels = {
  1: "aproape niciodată",
  2: "rar",
  3: "uneori",
  4: "des",
  5: "aproape mereu",
};

export const quizItems = [
  {
    id: "hard_01",
    pillarId: "hard",
    construct: "inițiere sub disconfort",
    reverseScored: false,
    text: "Ai în față o sarcină importantă pe care o simți grea, dar realizabilă. Cât de des faci primul contact concret înainte să apară urgența?",
    lowPattern: "amânare de contact",
    microIntervention: "2 minute de contact cu primul task greu.",
  },
  {
    id: "hard_02",
    pillarId: "hard",
    construct: "dependență de presiune",
    reverseScored: true,
    text: "Când ai un lucru relevant, dar fără termen imediat, îl lași în fundal până când presiunea te forțează să începi. Cât de des ai nevoie de stres ca să pornești?",
    lowPattern: "presiunea devine motorul principal",
    microIntervention: "Setează un deadline intern cu 24h mai devreme.",
  },
  {
    id: "hard_04",
    pillarId: "hard",
    construct: "pregătire ca evitare",
    reverseScored: true,
    text: "Petreci timp să organizezi, să citești sau să optimizezi instrumente, iar taskul esențial rămâne neatins. Cât de des pregătirea îți înlocuiește execuția?",
    lowPattern: "evitare sofisticată",
    microIntervention: "Maxim 15 minute pregătire, apoi 25 minute execuție.",
  },
  {
    id: "hard_06",
    pillarId: "hard",
    construct: "revenire după zi slabă",
    reverseScored: false,
    text: "Ai avut o zi în care ai evitat mult sau ai intrat în haos. Cât de des revii a doua zi cu un pas simplu și concret?",
    lowPattern: "abandon după o zi slabă",
    microIntervention: "Plan de restart de 10 minute pentru dimineața următoare.",
  },
  {
    id: "hard_08",
    pillarId: "hard",
    construct: "spargere în pași mici",
    reverseScored: false,
    text: "Când o sarcină pare mare, o traduci într-un prim pas clar și mic. Cât de des spargi lucrurile grele în pași de intrare?",
    lowPattern: "dificultatea pare globală și amorfă",
    microIntervention: "Scrie următorul pas fizic pentru taskul cheie.",
  },
  {
    id: "hard_12",
    pillarId: "hard",
    construct: "așteptarea motivației",
    reverseScored: true,
    text: "Când nu ai chef, amâni până când simți impulsul potrivit, în loc să te bazezi pe structură. Cât de des aștepți motivația înainte de acțiune?",
    lowPattern: "acțiunea depinde prea mult de dispoziție",
    microIntervention: "Începe după timer, nu după chef.",
  },
  {
    id: "night_01",
    pillarId: "night",
    construct: "tranziție seara",
    reverseScored: false,
    text: "Cu 60-90 de minute înainte de somn, încetinești ritmul: lumini mai blânde, activități mai liniștite, mai puține decizii grele. Cât de des faci o tranziție reală spre noapte?",
    lowPattern: "aterizare bruscă în somn",
    microIntervention: "Alarmă de început noapte la aceeași oră.",
  },
  {
    id: "night_02",
    pillarId: "night",
    construct: "telefon în pat",
    reverseScored: true,
    text: "Ajungi în pat cu intenția să dormi, dar telefonul deschide încă un fir: clipuri, mesaje, știri sau conversații. Cât de des patul devine loc de consum digital?",
    lowPattern: "telefonul captează somnul",
    microIntervention: "Telefonul se încarcă în afara patului.",
  },
  {
    id: "night_03",
    pillarId: "night",
    construct: "închidere mentală",
    reverseScored: false,
    text: "Seara, îți descarci din minte ce ai pe mâine ca să nu le cari în pat. Cât de des îți închizi mental ziua înainte de somn?",
    lowPattern: "gânduri deschise în pat",
    microIntervention: "Listă de mâine în 3 puncte înainte de culcare.",
  },
  {
    id: "night_08",
    pillarId: "night",
    construct: "munca trece în noapte",
    reverseScored: true,
    text: "Ziua se încheie, dar munca rămâne deschisă în minte și pe ecran, fără o limită clară. Cât de des lași munca să treacă peste spațiul somnului?",
    lowPattern: "muncă fără închidere",
    microIntervention: "Ritual de închidere a muncii la oră fixă.",
  },
  {
    id: "night_10",
    pillarId: "night",
    construct: "recuperare după noapte slabă",
    reverseScored: false,
    text: "După o noapte slabă, eviți să distrugi complet ritmul și revii la obiceiurile de bază în următoarea seară. Cât de des repari ritmul rapid, fără dramă?",
    lowPattern: "efect domino după o noapte slabă",
    microIntervention: "Protocol de reset după noapte proastă.",
  },
  {
    id: "night_11",
    pillarId: "night",
    construct: "oră de culcare protejată",
    reverseScored: false,
    text: "Ai o fereastră de somn pe care încerci să o protejezi chiar și când ziua nu a fost perfectă. Cât de des păstrezi o limită realistă pentru culcare?",
    lowPattern: "ora de somn se negociază prea ușor",
    microIntervention: "Alege o fereastră de culcare, nu o oră perfectă.",
  },
  {
    id: "start_01",
    pillarId: "start",
    construct: "wake anchor",
    reverseScored: false,
    text: "Dimineața, te trezești într-o fereastră relativ stabilă, chiar și după o zi mai dezordonată. Cât de des ai o ancoră de trezire?",
    lowPattern: "ritmul dimineții plutește",
    microIntervention: "Fereastră fixă de trezire timp de 7 zile.",
  },
  {
    id: "start_02",
    pillarId: "start",
    construct: "telefon dimineața",
    reverseScored: true,
    text: "În primele minute după trezire, telefonul îți preia atenția înainte ca tu să alegi direcția zilei. Cât de des începi ziua reactiv?",
    lowPattern: "telefonul setează tonul zilei",
    microIntervention: "Apă și lumină înainte de telefon.",
  },
  {
    id: "start_03",
    pillarId: "start",
    construct: "intenție de dimineață",
    reverseScored: false,
    text: "Înainte să intri în cerințele altora, îți clarifici ce contează azi. Cât de des alegi direcția zilei în mod explicit?",
    lowPattern: "ziua începe fără direcție proprie",
    microIntervention: "3 linii de intenție dimineața.",
  },
  {
    id: "start_06",
    pillarId: "start",
    construct: "lumină și corp",
    reverseScored: false,
    text: "După trezire, îi dai corpului semnale clare de zi: lumină, apă, mișcare ușoară. Cât de des îți activezi sistemul în mod blând?",
    lowPattern: "corp pornit greu",
    microIntervention: "10 minute lumină naturală dimineața.",
  },
  {
    id: "start_09",
    pillarId: "start",
    construct: "primul bloc profund",
    reverseScored: false,
    text: "Când ziua permite, protejezi un prim bloc de lucru important înainte de fragmentare. Cât de des începi cu ce contează cu adevărat?",
    lowPattern: "ziua este consumată de reactivitate",
    microIntervention: "Primul bloc de 25 minute pentru taskul cheie.",
  },
  {
    id: "start_10",
    pillarId: "start",
    construct: "reset de mediu",
    reverseScored: false,
    text: "Îți pregătești mediul de dimineață astfel încât alegerea bună să fie mai ușoară decât defaultul. Cât de des folosești mediul ca sprijin?",
    lowPattern: "mediul cere prea multe decizii",
    microIntervention: "Pregătește seara primul pas de dimineață.",
  },
  {
    id: "body_01",
    pillarId: "body",
    construct: "mișcare zilnică",
    reverseScored: false,
    text: "În zilele obișnuite, corpul tău primește mișcare suficientă pentru a simți că a participat la zi. Cât de des ai o bază de mișcare?",
    lowPattern: "corp sub-stimulat",
    microIntervention: "8-15 minute de mișcare zilnică.",
  },
  {
    id: "body_02",
    pillarId: "body",
    construct: "stat prelungit",
    reverseScored: true,
    text: "Rămâi multe ore pe scaun fără pauze reale de mișcare. Cât de des ziua îți ține corpul blocat?",
    lowPattern: "inactivitate acumulată",
    microIntervention: "Snack de mișcare la fiecare 90 de minute.",
  },
  {
    id: "body_04",
    pillarId: "body",
    construct: "forță minimă",
    reverseScored: false,
    text: "Îți antrenezi corpul suficient de des încât să simți că investești în versiunea ta viitoare. Cât de des faci o formă de forță sau rezistență?",
    lowPattern: "investiție fizică inconsistentă",
    microIntervention: "Două micro-sesiuni de forță pe săptămână.",
  },
  {
    id: "body_07",
    pillarId: "body",
    construct: "mobilitate seara",
    reverseScored: false,
    text: "Când corpul este tensionat seara, folosești mișcare ușoară sau mobilitate pentru a coborî ritmul. Cât de des ajuți corpul să aterizeze?",
    lowPattern: "tensiune corporală netranslatată",
    microIntervention: "5 minute mobilitate ușoară înainte de somn.",
  },
  {
    id: "body_11",
    pillarId: "body",
    construct: "minimum viable movement",
    reverseScored: false,
    text: "În zilele pline, păstrezi o versiune minimă de mișcare în loc să abandonezi complet. Cât de des menții firul?",
    lowPattern: "mișcarea cade când ziua devine grea",
    microIntervention: "Definește minimul: 2 minute, 10 genuflexiuni sau o plimbare.",
  },
  {
    id: "body_12",
    pillarId: "body",
    construct: "recuperare inteligentă",
    reverseScored: false,
    text: "Când ești obosit, alegi recuperare reală sau mișcare blândă, nu doar inerție pe ecran. Cât de des îți recuperezi corpul activ?",
    lowPattern: "oboseală gestionată prin inerție",
    microIntervention: "Plimbare ușoară sau stretching în loc de scroll prelungit.",
  },
  {
    id: "food_01",
    pillarId: "food",
    construct: "primă masă stabilă",
    reverseScored: false,
    text: "Prima masă a zilei îți oferă stabilitate, nu doar un vârf rapid de energie. Cât de des incluzi proteină, fibre sau ceva consistent?",
    lowPattern: "energie instabilă din start",
    microIntervention: "Proteină + fibre la prima masă.",
  },
  {
    id: "food_02",
    pillarId: "food",
    construct: "sărit mese",
    reverseScored: true,
    text: "Ziua devine aglomerată și amâni mâncarea până ajungi seara foarte flămând. Cât de des ajungi să decizi alimentația sub presiune?",
    lowPattern: "foame acumulată seara",
    microIntervention: "Pregătește o opțiune de masă de urgență.",
  },
  {
    id: "food_03",
    pillarId: "food",
    construct: "hidratare",
    reverseScored: false,
    text: "Pe parcursul zilei, bei suficientă apă încât oboseala să nu fie amplificată de deshidratare. Cât de des îți susții energia prin hidratare?",
    lowPattern: "hidratare uitată",
    microIntervention: "Un pahar de apă legat de fiecare masă.",
  },
  {
    id: "food_07",
    pillarId: "food",
    construct: "cofeină inteligentă",
    reverseScored: false,
    text: "Folosești cofeina cu o limită care îți respectă somnul de seară. Cât de des ai un gard clar pentru cafea sau energizante?",
    lowPattern: "cofeina repară ziua și taxează noaptea",
    microIntervention: "Alege o oră limită pentru cofeină.",
  },
  {
    id: "food_10",
    pillarId: "food",
    construct: "cină realistă",
    reverseScored: false,
    text: "Seara, alegi o cină suficient de simplă și potrivită încât să nu îți îngreuneze somnul. Cât de des faci cina compatibilă cu noaptea?",
    lowPattern: "cina devine prea târzie sau prea grea",
    microIntervention: "Cină simplă repetabilă pentru zile încărcate.",
  },
  {
    id: "food_12",
    pillarId: "food",
    construct: "rușine alimentară",
    reverseScored: true,
    text: "Când mănânci diferit de plan, intri în vină sau reguli dure, în loc să revii calm la următoarea alegere. Cât de des alimentația devine auto-judecată?",
    lowPattern: "vină în loc de reglare",
    microIntervention: "Următoarea alegere simplă, fără pedeapsă.",
  },
  {
    id: "attention_01",
    pillarId: "attention",
    construct: "protecția tranzițiilor",
    reverseScored: false,
    text: "Între două taskuri, observi impulsul de telefon și protejezi tranziția. Cât de des nu lași pauzele mici să devină captură digitală?",
    lowPattern: "tranziții capturate",
    microIntervention: "Respiră 30 secunde înainte de telefon.",
  },
  {
    id: "attention_02",
    pillarId: "attention",
    construct: "notificări",
    reverseScored: true,
    text: "Notificările îți fragmentează atenția și îți mută ziua în direcțiile altora. Cât de des ești întrerupt înainte să alegi tu?",
    lowPattern: "atenție dictată de notificări",
    microIntervention: "Bloc silențios de notificări.",
  },
  {
    id: "attention_04",
    pillarId: "attention",
    construct: "single-tasking",
    reverseScored: false,
    text: "Când lucrezi la ceva important, creezi condiții pentru un singur fir de atenție. Cât de des îți protejezi focusul?",
    lowPattern: "taskuri amestecate",
    microIntervention: "Single-tab rule pentru 25 minute.",
  },
  {
    id: "attention_05",
    pillarId: "attention",
    construct: "telefon în blocuri de lucru",
    reverseScored: true,
    text: "În timpul unui bloc de lucru, telefonul rămâne suficient de aproape încât să îl verifici automat. Cât de des proximitatea telefonului îți rupe focusul?",
    lowPattern: "telefonul este prea accesibil",
    microIntervention: "Telefonul în altă cameră pentru un sprint.",
  },
  {
    id: "attention_09",
    pillarId: "attention",
    construct: "cap de seară informațional",
    reverseScored: false,
    text: "Seara, limitezi fluxul de informații ca mintea să nu rămână aprinsă. Cât de des ai o margine clară pentru input digital?",
    lowPattern: "minte aprinsă de informație",
    microIntervention: "Cap de informație cu 30 minute înainte de somn.",
  },
  {
    id: "attention_10",
    pillarId: "attention",
    construct: "captură de distrageri",
    reverseScored: false,
    text: "Când apare o idee sau un impuls lateral, îl notezi și revii la ce făceai. Cât de des poți captura distragerea fără să o urmezi?",
    lowPattern: "impulsurile devin direcție",
    microIntervention: "Distraction capture pad.",
  },
  {
    id: "social_01",
    pillarId: "social",
    construct: "contact intențional",
    reverseScored: false,
    text: "Într-o săptămână obișnuită, inițiezi contact real cu oameni importanți, nu doar reacționezi la mesaje. Cât de des construiești conexiunea activ?",
    lowPattern: "conexiune lăsată la întâmplare",
    microIntervention: "Un reach-out intențional pe zi.",
  },
  {
    id: "social_02",
    pillarId: "social",
    construct: "cerere de sprijin",
    reverseScored: false,
    text: "Când simți că sistemul e încărcat, ceri sprijin înainte să ajungi în criză. Cât de des nu duci totul singur?",
    lowPattern: "sprijin cerut prea târziu",
    microIntervention: "Ask before crisis: mesaj scurt către o persoană sigură.",
  },
  {
    id: "social_03",
    pillarId: "social",
    construct: "izolare sub stres",
    reverseScored: true,
    text: "Când ești stresat, te retragi și devii mai greu de găsit, chiar când ai avea nevoie de contact. Cât de des stresul te izolează?",
    lowPattern: "izolare ca reflex de stres",
    microIntervention: "10 minute contact uman în ziua grea.",
  },
  {
    id: "social_05",
    pillarId: "social",
    construct: "sinceritate dozată",
    reverseScored: false,
    text: "În relațiile sigure, poți spune pe scurt cum ești cu adevărat, fără să transformi totul într-o povară. Cât de des lași oamenii potriviți să te vadă?",
    lowPattern: "starea reală rămâne ascunsă",
    microIntervention: "Răspuns sincer scurt la întrebarea cum ești.",
  },
  {
    id: "social_09",
    pillarId: "social",
    construct: "co-reglare",
    reverseScored: false,
    text: "Când ești agitat, folosești prezența umană ca sprijin de reglare, nu doar strategii solitare. Cât de des folosești co-reglarea intenționat?",
    lowPattern: "autoreglare exclusiv solitară",
    microIntervention: "Listă de 2 persoane pentru apel de reglare.",
  },
  {
    id: "social_12",
    pillarId: "social",
    construct: "ascunderea stării reale",
    reverseScored: true,
    text: "Spui automat că ești bine chiar și când nu ești, de teamă să nu deranjezi sau să pari slab. Cât de des îți ascunzi starea reală?",
    lowPattern: "mascare emoțională",
    microIntervention: "O propoziție sinceră într-un context sigur.",
  },
  {
    id: "trust_01",
    pillarId: "trust",
    construct: "promisiuni mici ținute",
    reverseScored: false,
    text: "Îți faci promisiuni mici, realizabile, și le respecți suficient de des încât să te poți baza pe tine. Cât de des te ții de ce ți-ai promis?",
    lowPattern: "credibilitate personală fragilă",
    microIntervention: "O promisiune minimă zilnică.",
  },
  {
    id: "trust_03",
    pillarId: "trust",
    construct: "revenire fără dramă",
    reverseScored: false,
    text: "Când ratezi un obicei, nu transformi episodul într-o identitate; repari și continui. Cât de des revii repede după derapaje?",
    lowPattern: "ratarea devine poveste despre sine",
    microIntervention: "Fraza: am ratat, reiau acum.",
  },
  {
    id: "trust_04",
    pillarId: "trust",
    construct: "etichetă fixă",
    reverseScored: true,
    text: "După o perioadă slabă, îți spui că așa ești tu și renunți la posibilitatea de ajustare. Cât de des folosești etichete fixe?",
    lowPattern: "identitate blocată după dificultate",
    microIntervention: "Înlocuiește eticheta cu: acum învăț să...",
  },
  {
    id: "trust_06",
    pillarId: "trust",
    construct: "review fără rușine",
    reverseScored: false,
    text: "Când îți revizuiești săptămâna, cauți lecții aplicabile, nu motive de autoatac. Cât de des faci review constructiv?",
    lowPattern: "reflecție dureroasă sau evitată",
    microIntervention: "Ce a mers, ce n-a mers, ce ajustez.",
  },
  {
    id: "trust_08",
    pillarId: "trust",
    construct: "promisiuni rupte repetat",
    reverseScored: true,
    text: "Îți promiți frecvent că de mâine schimbi ceva, dar promisiunea se rupe repede și ciclul se repetă. Cât de des intri în acest tipar?",
    lowPattern: "ciclu promisiune-ruptură-vină",
    microIntervention: "Promisiuni doar pe 24h, nu pe termen vag.",
  },
  {
    id: "trust_13",
    pillarId: "trust",
    construct: "continuitate în imperfecțiune",
    reverseScored: false,
    text: "În zilele în care nu iese ideal, faci totuși o acțiune care păstrează firul. Cât de des îți menții continuitatea în imperfecțiune?",
    lowPattern: "firul se rupe când ziua nu e ideală",
    microIntervention: "Acțiunea de 1% în fiecare zi grea.",
  },
];
