export const systemMapContent = {
  hard: {
    phase: "Zi activă",
    phaseLabel: "fricțiune utilă",
    systemRole: "Reduce datoria psihologică a evitării și lasă seara cu mai puține bucle deschise.",
    whenStable: "Intri devreme în primul lucru greu, chiar imperfect, iar mintea primește dovada că nu trebuie să aștepte panica pentru a acționa.",
    whenBroken: "Taskurile importante rămân în fundal, presiunea crește, iar seara devine un inventar mental al lucrurilor neatinse.",
    sleepCost: "Ruminația de seară crește: corpul e obosit, dar mintea încă negociază cu ce a evitat peste zi.",
    microShift: "Alege un task greu și fă doar 2 minute de contact real cu el: deschide fișierul, scrie primul rând, trimite primul mesaj.",
    reflectionQuestion: "Ce lucru mic, dar greu, dacă îl atingi azi, îți face seara mai liberă?",
    connections: ["trust", "attention", "night"],
  },
  night: {
    phase: "Seara",
    phaseLabel: "pistă de aterizare",
    systemRole: "Transformă seara într-o tranziție, nu într-o prăbușire directă din stimulare în pat.",
    whenStable: "Lumina, ecranele, munca și deciziile scad treptat; ziua se închide înainte ca somnul să fie forțat.",
    whenBroken: "Telefonul, munca și conținutul intens intră în pat, iar creierul primește semnal de zi exact când are nevoie de noapte.",
    sleepCost: "Adormirea devine mai fragilă, iar noaptea începe cu activare cognitivă, nu cu siguranță.",
    microShift: "Setează o alarmă de început de noapte și scrie trei lucruri pentru mâine înainte să intri în pat.",
    reflectionQuestion: "Ce semnal simplu îi poate spune corpului tău: ziua s-a încheiat?",
    connections: ["attention", "food", "start"],
  },
  start: {
    phase: "Dimineața",
    phaseLabel: "sistem de operare",
    systemRole: "Setează direcția atenției înainte ca ziua să fie confiscată de zgomotul extern.",
    whenStable: "Te trezești într-o fereastră relativ stabilă, iei lumină, apă și o intenție mică înainte de telefon.",
    whenBroken: "Ziua începe reactiv: notificări, scroll, grabă și decizii luate din inerție.",
    sleepCost: "O dimineață fără ancoră împinge haosul în zi, iar haosul se întoarce seara ca oboseală agitată.",
    microShift: "Primele 10 minute: apă, lumină, o frază despre ce contează azi. Telefonul după aceea.",
    reflectionQuestion: "Cine alege primul ton al zilei tale: tu sau telefonul?",
    connections: ["attention", "hard", "trust"],
  },
  body: {
    phase: "Zi activă",
    phaseLabel: "energie biologică",
    systemRole: "Folosește corpul ca infrastructură pentru energie, stres mai digerabil și presiune sănătoasă de somn.",
    whenStable: "Mișcarea apare în versiuni realiste: mers, forță minimă, mobilitate, pauze scurte din statul prelungit.",
    whenBroken: "Corpul rămâne blocat toată ziua, iar seara încearcă să descarce tensiune prin ecran sau inerție.",
    sleepCost: "Presiunea de somn și reglarea stresului pot deveni inconsistente; oboseala se simte grea, dar nu liniștită.",
    microShift: "Fă 8 minute de mișcare ușoară sau o plimbare după masă. Minimum viabil, nu performanță.",
    reflectionQuestion: "Ce formă de mișcare ar face corpul tău să simtă că a participat la zi?",
    connections: ["food", "night", "trust"],
  },
  food: {
    phase: "Zi activă",
    phaseLabel: "stabilitate metabolică",
    systemRole: "Stabilizează energia și reduce deciziile alimentare luate seara sub presiune.",
    whenStable: "Prima masă e suficient de solidă, hidratarea nu e uitată, iar cofeina are o limită care respectă noaptea.",
    whenBroken: "Ziua e ținută pe cafea și amânare, apoi seara vine cu foame, impulsivitate și vinovăție.",
    sleepCost: "Cina târzie, cofeina sau fluctuațiile de energie pot muta corpul din modul de recuperare în modul de procesare.",
    microShift: "Alege o masă de bază repetabilă: proteină, fibre, apă. Simplu și suficient.",
    reflectionQuestion: "Unde folosești mâncarea ca reparație târzie pentru o zi nesusținută?",
    connections: ["body", "attention", "night"],
  },
  attention: {
    phase: "Toată ziua",
    phaseLabel: "protecția semnalului",
    systemRole: "Păstrează atenția suficient de întreagă încât ziua să poată fi închisă, nu doar consumată.",
    whenStable: "Telefonul are margini, notificările nu conduc ziua, iar tranzițiile nu sunt capturate automat.",
    whenBroken: "Ziua pare plină, dar rămâne fragmentată: multe intrări, puține închideri, minte aprinsă seara.",
    sleepCost: "Somnul este taxat de input neterminat: creierul continuă să proceseze după ce corpul vrea să se oprească.",
    microShift: "Un sprint de 25 de minute cu telefonul în altă cameră și o foaie pentru impulsuri laterale.",
    reflectionQuestion: "Care este momentul zilei în care atenția ta este cel mai ușor cumpărată?",
    connections: ["start", "hard", "night"],
  },
  social: {
    phase: "Reglare umană",
    phaseLabel: "co-reglare",
    systemRole: "Reduce costul de a duce totul singur și transformă conexiunea în infrastructură de reglare.",
    whenStable: "Există contact intenționat, sinceritate dozată și oameni către care poți trimite un semnal înainte de criză.",
    whenBroken: "Stresul te izolează, răspunzi automat că ești bine, iar seara devine locul unde tot ce ai ținut singur se adună.",
    sleepCost: "Activarea emoțională rămâne nerezolvată; corpul intră în noapte cu senzația că trebuie să rămână de gardă.",
    microShift: "Trimite un mesaj simplu unei persoane sigure: nu trebuie să fie dramatic, doar real.",
    reflectionQuestion: "Ce parte din stresul tău devine mai grea pentru că o duci singur?",
    connections: ["trust", "night", "attention"],
  },
  trust: {
    phase: "Mâine",
    phaseLabel: "dovezi de identitate",
    systemRole: "Construiește încredere prin promisiuni mici ținute, nu prin reguli mari după zile slabe.",
    whenStable: "Îți promiți lucruri suficient de mici încât să le poți respecta și revii fără dramă când pierzi firul.",
    whenBroken: "Promisiunile devin prea mari, se rup, apoi vina produce reguli mai dure și mai puțină încredere.",
    sleepCost: "Seara poate deveni proces de auto-judecată: nu doar ce s-a întâmplat azi, ci ce crezi că spune despre tine.",
    microShift: "Alege o promisiune sub 10 minute și trateaz-o ca pe o dovadă, nu ca pe un test de caracter.",
    reflectionQuestion: "Ce promisiune mică ți-ar repara relația cu tine fără să-ți ceară o viață perfectă?",
    connections: ["hard", "start", "social"],
  },
};

export const systemMapModes = [
  {
    id: "map",
    label: "Harta sistemului",
    description: "Vezi cei 8 piloni ca roluri într-un sistem de zi întreagă.",
  },
  {
    id: "flow",
    label: "Ziua în flux",
    description: "Urmărește cum dimineața, ziua activă, seara și mâine se influențează reciproc.",
  },
  {
    id: "links",
    label: "Legături",
    description: "Observă dependențele: când un pilon cade, ce alte zone devin vulnerabile.",
  },
];

export const dayFlow = ["Dimineața", "Zi activă", "Toată ziua", "Reglare umană", "Seara", "Mâine"];
